### ISSUE TITLE
Add instructions in README

### ISSUE THREAD

**Issue by naderghanbari** [lancegatlin/sbt-release-gitflow#1]
It would be great if you add some instructions on how to use this plugin.

**Comment by lancegatlin** [comment]
Hey! Thanks for your interest. I'm not a fan of gitflow and created this plugin for my current job since they have too much sunk cost in gitflow at this point to turn back. I will write some docs for it over the break, but its def not by best code haha.

**Comment by lancegatlin** [comment]
Done!
